import {
  FaReact,
  FaAngular,
  FaVuejs,
  FaNodeJs,
  FaHtml5,
  FaCss3Alt,
  FaSass,
  FaBootstrap,
  FaPython,
  FaJava,
  FaPhp,
  FaSwift,
  FaWordpress,
  FaMagento,
  FaGit,
  FaGithub,
  FaGitlab,
  FaBitbucket,
  FaNpm,
  FaYarn,
  FaDocker,
  FaAws,
  FaGoogle,
  FaMicrosoft,
  FaApple,
  FaLinux,
  FaWindows,
  FaFirefox,
  FaChrome,
  FaEdge
} from "react-icons/fa";

const brandIcons = [
  { icon: <FaReact />, name: "React" },
  { icon: <FaAngular />, name: "Angular" },
  { icon: <FaVuejs />, name: "Vue.js" },
  { icon: <FaNodeJs />, name: "Node.js" },
  { icon: <FaHtml5 />, name: "HTML5" },
  { icon: <FaCss3Alt />, name: "CSS3" },
  { icon: <FaSass />, name: "Sass" },
  { icon: <FaBootstrap />, name: "Bootstrap" },
  { icon: <FaPython />, name: "Python" },
  { icon: <FaJava />, name: "Java" },
  { icon: <FaPhp />, name: "PHP" },
  { icon: <FaSwift />, name: "Swift" },
  { icon: <FaWordpress />, name: "WordPress" },
  { icon: <FaMagento />, name: "Magento" },
  { icon: <FaGit />, name: "Git" },
  { icon: <FaGithub />, name: "GitHub" },
  { icon: <FaGitlab />, name: "GitLab" },
  { icon: <FaBitbucket />, name: "Bitbucket" },
  { icon: <FaNpm />, name: "npm" },
  { icon: <FaYarn />, name: "Yarn" },
  { icon: <FaDocker />, name: "Docker" },
  { icon: <FaAws />, name: "AWS" },
  { icon: <FaGoogle />, name: "Google" },
  { icon: <FaMicrosoft />, name: "Microsoft" },
  { icon: <FaApple />, name: "Apple" },
  { icon: <FaLinux />, name: "Linux" },
  { icon: <FaWindows />, name: "Windows" },
  { icon: <FaFirefox />, name: "Firefox" },
  { icon: <FaChrome />, name: "Chrome" },
  { icon: <FaEdge />, name: "Edge" }
];

export default brandIcons;
